### PR TITLE
#DP-81 Fix: Login redirection

### PR DESCRIPTION
**Pull request by feyton**
### What the PR does
This pull request fix the redirection issue upon success login after an attempt to access protected route. The following tasks has been completed

- [x] The user is redirected to the requested pages
- [x] The user receives a warning when accessing protected route

### Background context
This PR will fix an open issue and boost user experience since they will not have to remember the route requested after a successful login

### How should this be manually tested
When you try to access the protected route ex `/dashboard/trainee` you will receive a warning that you are trying to access a route that requires login. Instead of redirecting to the default `dashboard` you will be redirected to the requested route
To manually test this:
1. Open the site following link: [https://devpulse-review-app-49.herokuapp.com/dashboard/calendar](https://devpulse-review-app-49.herokuapp.com/dashboard/calendar)
2. Do a successful login
3. Check the redirect

### Screenshot if applicable
image

### CODE REVIEW

**Comment by feyton** [comment]
I deployed a review app for you to try out this pull request 👇🏽

Heroku App: https://devpulse-review-app-49.herokuapp.com/


<hidden purpose="for-rewritable-pr-comment-action-use" value="Deploy"></hidden>

**Review by PatrickTUy — APPROVED** [review]
This looks good

**Review by PatrickTUy — CHANGES_REQUESTED** [review]
Can we also have the coverage increased,  the coverage decreased a little bit.

**Review by PatrickTUy — APPROVED** [review]
This looks better

**Review by jeandamascyifuzo — APPROVED** [review]
Good job @feyton

**Review by chanceDira — APPROVED** [review]
Working perfectly fine. good job.

**Pull request merged**
