### PR TITLE
#DP-55 chore: CI/CD configuration

### PR DESCRIPTION
**Pull request by samyshyaka**
#### What does this PR do?
Configured a continuous integration pipeline using GitHub Actions and Heroku. The continuous integration service should automatically run tests and other preliminary build steps required to ship the next iteration of the product

#### Description of the tasks to be completed
- [x] GitHub Actions is configured as a continuous integration service used to build and test the app.
- [x] Heroku Pipeline is configured
- [x] GitHub Actions and coveralls badges have been added to the repo

#### How should this be manually tested?
```js
git checkout ch-cicd-dp-55
git fetch
npm install
git add .
git commit
git push
```
#### Pre-requisites:

- Clone the project

#### Relevant trello story:
[#DP-55](https://trello.com/c/inUJiGlS/55-ci-cd)

### CODE REVIEW

**Review by feyton — CHANGES_REQUESTED** [review]
Hello @samyshyaka 
This is well implemented tough, we need to add `coverage` directory in `.gitignore`
After that you can remove all cached versions with following command
```
git rm --cached coverage -r
```
This will ensure that the coverage files that were accidentally tracked are removed from GitHub

**Review by feyton — APPROVED** [review]
### Approval
This is well implemented @samyshyaka and can be merged

**Review by jeandamascyifuzo — APPROVED** [review]
Great job @samyshyaka

**Review by chanceDira — APPROVED** [review]
Great work 👍

**Review by ceelogre — APPROVED** [review]

**Pull request merged**
