### PR TITLE
Ft-create dashboard cards

### LINKED ISSUE #245: Adding a trainee to a cohort
# Description
Adding a trainee to a cohort produces an error. For the first time, it says: `startingPath is required` and for all subsequent trials, it shows the error below.

image

### PR DESCRIPTION
**Pull request by chrill-christella**
### PR Description

- coordinator and manager cards should display all teams they manage, their average ratings and status of trainees

### Description of tasks that were expected to be completed

- Each team has its own card
- Cards are color-represented for example, red means the team is underperforming.
- All data points from the Figma design are implemented

### How has this been tested?

- checkout to branch ft-create-dashboard cards
- npm i
- npm run dev
- login as a coordinator or an admin or manager
- please make sure that you have  ttls so that you will be able to create a team 
- navigate to trainees on the sidebar and add some trainees
- navigate to ratings and rate different trainees
- navigate to teams
- you will be able to see teams cards with corresponding trainees and their ratings

### CODE REVIEW

**Review by patsicko — APPROVED** [review]

**Comment by ericndungutse** [comment]
I cannot add a team . When I try, I receive an arror.

**Review by Martha-Iradukunda — APPROVED** [review]

**Review by teerenzo — APPROVED** [review]

**Review by Fidela1 — COMMENTED** [review]
Adding team  is not working when I try to add it I get error

**Review by Patienceineza — APPROVED** [review]
LGTM

**Review by Fidela1 — APPROVED** [review]

**Review by ceelogre — CHANGES_REQUESTED** [review]
Perform a live logging on the deployed version as it's not working.

**Review by ceelogre — APPROVED** [review]

**Pull request merged**
