### PR TITLE
DP-120 Signup-enhancement

### PR DESCRIPTION
**Pull request by PatrickTUy**
# PR Description
This PR enhanced signup page by adding other fields that are essential for the profile of the created user.
# Description of tasks that were expected to be completed
Add date of birth, first name , last name, and gender fields when signing up.
# How has this been tested?
   On the nav bar click sign in and then click signup and fill in the fields to sign up
   Log in a coordinator or admin to give the new created user a cohort so as to have an organization they will be logging in.
   Log in the new user, their names can be found in the profile section.
   checkout this BE [PR](https://github.com/atlp-rwanda/atlp-pulse-bn/pull/42) the review app is connected to.
# Number of Commits
1
# Screenshots (If appropriate)
N/A
# Please check this Checklist before you submit your PR:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My code generate no warnings
- [x] My test coverage meet the set test coverage threshold
- [x] There are no vulnerabilities
- [x] There are no conflicts with the base branch

### CODE REVIEW

**Comment by Procech20** [comment]
I deployed a review app for you to try out this pull request 👇🏽
Heroku App: https://devpulse-review-app-141.herokuapp.com/


<hidden purpose="for-rewritable-pr-comment-action-use" value="Deploy"></hidden>

**Review by Tsa2341 — APPROVED** [review]

**Review by Procech20 — APPROVED** [review]
Works. And profiles gets created with necessary fields

**Review by Placide123 — APPROVED** [review]

**Review by Himbaza123h — APPROVED** [review]
Great!

**Review by ceelogre — CHANGES_REQUESTED** [review]
Although this usecase works well, there might be some changes needed in the design. Think about this question, if I signup, how does an admin know which org to add me to? That means they should be able to identify my credentials (say by asking people to use work emails like email@ur.ac.rw which would indicate that this user is from university of rwanda org) and this is not a task we want them to have since any random user can create an account.

My suggestion is that this signup page be put behind Org login (which guarantees that this user has been invited) and the one without org login should only be for creating organizations.

**Comment by PatrickTUy** [comment]
> Although this usecase works well, there might be some changes needed in the design. Think about this question, if I signup, how does an admin know which org to add me to? That means they should be able to identify my credentials (say by asking people to use work emails like [email@ur.ac.rw](mailto:email@ur.ac.rw) which would indicate that this user is from university of rwanda org) and this is not a task we want them to have since any random user can create an account.
> 
> My suggestion is that this signup page be put behind Org login (which guarantees that this user has been invited) and the one without org login should only be for creating organizations.

Yes, this has to be worked on as an improvement.

**Review by ceelogre — COMMENTED** [review]
Resolve conflicts for us to move forward.

**Comment by PatrickTUy** [comment]
> Resolve conflicts for us to move forward.

I've resolved them.

**Review by ceelogre — APPROVED** [review]

**Pull request merged**
