### PR TITLE
Login and signup new theme

### PR DESCRIPTION
**Pull request by edwinnambaje**
# PR Description

- This Pr is for updating our login and signup themes

# Description of tasks that were expected to be completed

List all the tasks and sub-tasks that were assigned to you or that you assigned yourself. Make sure you check evey completed task.

# How has this been tested?

Please describe the tests that you ran to verify your functionalities. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

# Number of Commits

The number of commits should not exceed **2 commits**. In case they are more than that, please take your time and squash them.

# Screenshots (If appropriate)
Screenshot 2023-08-21 at 01 48 24
Screenshot 2023-08-21 at 01 48 15

# Please check this Checklist before you submit your PR:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My code generate no warnings
- [ ] My test coverage meet the set test coverage threshold
- [ ] There are no vulnerabilities
- [ ] There are no conflicts with the base branch

### CODE REVIEW

**Review by Kevin-ishimwe — APPROVED** [review]
works as expected

**Review by blackd44 — APPROVED** [review]

**Review by Patienceineza — APPROVED** [review]
lgtm

**Review by AbdulKhaliq59 — APPROVED** [review]
LGTM

**Review by patsicko — APPROVED** [review]

**Review by ceelogre — CHANGES_REQUESTED** [review]
There's a mix of languages when you select a different language than english. Also, the title should only read `Bienvenue a Andela` that means remove `.devpulse.org`
image

**Comment by edwinnambaje** [comment]
> There's a mix of languages when you select a different language than english. Also, the title should only read `Bienvenue a Andela` that means remove `.devpulse.org` image

You can check again i have added requested changes

**Review by ceelogre — APPROVED** [review]

**Pull request merged**
