### PR TITLE
 Update invitation  

### PR DESCRIPTION
**Pull request by GSinseswa721**
# PR Description

This PR implements updates for the invitation. It includes changes to the invitation update functionality and improvements to the modal handling.

# Description of tasks that were expected to be completed

- [x] Updated the GraphQL updateInvitation mutation.
- [x] Fixed bugs related to missing arguments in the mutation.
- [x] Ensured data is fetched properly from the database.

# How has this been tested?

- Visit [this Link](https://metron-devpulse-git-ft-update-invitation-metron.vercel.app/)
- Use the email address devpulse@proton.me and the password Test@12345 to log in.
- Access the invitation page by using the sidebar.
- Click the 3-dot button in the table on the opposite side and follow to the direction.

# Screenshots (If appropriate)

Screenshot (12)
Screenshot (8)
Screenshot (6)

### CODE REVIEW

**Review by Sophie20202 — APPROVED** [review]

**Review by Ndevu12 — APPROVED** [review]

**Review by niyobertin — APPROVED** [review]

**Comment by ncutixavier** [comment]
- Resolve conflicts
- When updating, you should populate the input

image

**Comment by GSinseswa721** [comment]
> * Resolve conflicts
> * When updating, you should populate the input
> 
> image

Solved sir..

**Comment by ncutixavier** [comment]
@GSinseswa721  & @niyobertin 
- As an admin, I should be able to update all invitation data (including status)
- These button need more styles, Please check how other buttons styled
image

**Comment by GSinseswa721** [comment]
> @GSinseswa721 & @niyobertin
> 
> * As an admin, I should be able to update all invitation data (including status)
> * These button need more styles, Please check how other buttons styled
>   image

@ncutixavier do I've to update all status sir, like invitation that has been accepted by the user already or decline one? Or I keep on updating only pending invitation ?

**Review by niyobertin — APPROVED** [review]

**Review by Oliviier-dev — APPROVED** [review]

**Review by ncutixavier — APPROVED** [review]

**Pull request merged**
