### PR TITLE
 #384 ttl rating trainees

### LINKED ISSUE #384: Allow TTLs to rate
# Description

The app should allow TTLs to rate not just managers.

### PR DESCRIPTION
**Pull request by pacifiquemboni**
# PR Description

The app should allow TTLs to rate not just managers.

# How has this been tested?

Clone the project `https://github.com/atlp-rwanda/atlp-pulse-fn.git` switch to `ttl-rating-trainee` branch.
 for back end clone this `https://github.com/atlp-rwanda/atlp-pulse-bn.git` switch to `fx-allow-ttl-to-rate` branch
 
 include all env variables for both backend and front end then install all dependencies `npm install` and run with `npm run dev`
Login as ttl and see if you can rate available tarinees

# Screenshots (If appropriate)

Screenshot 2024-09-13 125202

### CODE REVIEW

**Review by igorihimbazwe — APPROVED** [review]

**Comment by aimedivin** [comment]
@pacifiquemboni , @igorihimbazwe 
Please review the coordinator's process for rating a trainee and resolve the issue
image

**Review by elijahladdie — APPROVED** [review]

**Comment by aimedivin** [comment]
@pacifiquemboni , @igorihimbazwe 
Pls ensure the close icon for the rating modal is functioning properly.
image

**Review by aimedivin — APPROVED** [review]
Work on requested changes

**Review by aimedivin — CHANGES_REQUESTED** [review]
Work on requested changes

**Review by aimedivin — APPROVED** [review]

**Pull request merged**
