### PR TITLE
export ratings data into CSV/Excel formats

### PR DESCRIPTION
**Pull request by oliviertech212**
# PR Description

 export ratings data into CSV/Excel formats.

# Description of tasks that were expected to be completed

a user will be able to export ratings data into CSV/Excel formats.

# How has this been tested?

- checkout to branch `ft-Export-data`
- run `npm i`
- run `npm run dev`
- log in as a trainee
- navigate to Performance 

# Screenshots 
image

image

### CODE REVIEW

**Review by ceelogre — COMMENTED** [review]
Let's first get the rest of the reviews.

**Review by blackd44 — CHANGES_REQUESTED** [review]
Screenshot 2023-07-19 at 09 55 10

check why clicking on `export data` isn't working on deployed version

**Review by blackd44 — APPROVED** [review]

**Review by UwaweTera — APPROVED** [review]

**Review by ericndungutse — APPROVED** [review]
LGTM

**Review by Patienceineza — APPROVED** [review]
LGTM

**Review by ceelogre — CHANGES_REQUESTED** [review]
Work with @blackd44 to integrate well with ratings. I'm unable to add a rating so that I can view new data for export.

**Review by ceelogre — APPROVED** [review]

**Pull request merged**
