### PR TITLE
fix attendance page

### PR DESCRIPTION
**Pull request by blackd44**
# PR Description
fixing attendance pages

# Description of tasks that were expected to be completed
- fixing attendance links and routes, [issues No 268](https://github.com/atlp-rwanda/atlp-pulse-fn/issues/268)

# How has this been tested?
**for local**
- clone the github
- run `npm install`
- run `npm run dev`
- open your browser to open the local Website

**for deployed version**
- open the link below: https://metron-devpulse-git-fix-attendence-page-metron.vercel.app/

**after opening the browser
- login as `coordinator` or `trainee`
- the view in side navigation bar, click on `Attendance` to open attendance page

# Number of Commits

**1 commits**

# Screenshots (If appropriate)
Screenshot 2023-08-22 at 20 42 25

# Please check this Checklist before you submit your PR:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My code generate no warnings
- [x] My test coverage meet the set test coverage threshold
- [x] There are no vulnerabilities
- [x] There are no conflicts with the base branch

### CODE REVIEW

**Review by edwinnambaje — APPROVED** [review]

**Review by IMANISHIMWETelesphore — APPROVED** [review]

**Review by Habihirwe — APPROVED** [review]

**Review by ceelogre — CHANGES_REQUESTED** [review]
Unable to login.
image

**Comment by blackd44** [comment]
> Unable to login. image

Sam you can check again
it was the issue in backend

**Review by ceelogre — COMMENTED** [review]
Why is it that only one trainee appears on the list yet when you go to attendance, they are two?
image
image

**Comment by blackd44** [comment]
> Why is it that only one trainee appears on the list yet when you go to attendance, they are two? image image

hello Sam,
now it's working
Screenshot 2023-08-25 at 08 05 24
Screenshot 2023-08-25 at 08 06 22

**Review by ceelogre — APPROVED** [review]

**Pull request merged**
