### PR TITLE
#DP-103 feat: Profile settings integration

### PR DESCRIPTION
**Pull request by samyshyaka**
### What does this PR do?
This pull request allow the user to update their profile data to the database as it integrates the back-end with the frontend.
The user will be able to persist the data to the database

### Description of the tasks to be completed
- [x] A user should be able to edit their personal info
- [x] A user should be able to change their avatar
 
### How should this be manually tested?
Use the heroku-review app linked to this pull request or click the link below.
[https://devpulse-review-app-82.herokuapp.com/](https://devpulse-review-app-82.herokuapp.com/)

To test on your machine:

1. Be sure to clone the project (Backend and Frontend)
2. Checkout the respective branches for both the backend and frontend
3. Follow the steps below for the frontend

```js
git fetch
npm install
// create .env file and add the following line
// BACKEND_URL=<the link to your backend link>
npm run dev
open http://localhost:3000/
```
### Pre-requisites:
- Have both the backend and frontend projects

### Relevant trello story:
[#DP-103](https://trello.com/c/X4G3QkHh/103-profile-settings-integration)

### CODE REVIEW

**Comment by feyton** [comment]
I deployed a review app for you to try out this pull request 👇🏽

Heroku App: https://devpulse-review-app-82.herokuapp.com/


<hidden purpose="for-rewritable-pr-comment-action-use" value="Deploy"></hidden>

**Review by jeandamascyifuzo — APPROVED** [review]
well done

**Review by PatrickTUy — DISMISSED** [review]
good job @samyshyaka can you describe a more detailed way on how to test this, because cloning and running the app on your branch is bringing an unceasing skeleton on the profile settings.
Also raise the coverage as it has dropped.

**Review by feyton — APPROVED** [review]

**Review by Dev-nkundineza — APPROVED** [review]
Good work @feyton

**Pull request merged**
