### PR TITLE
#DP-106 Feat: Rate trainees

### LINKED ISSUE #76: Rate trainees
# Description

Let's add the ability to rate trainees since we can't find any trace of it.

### PR DESCRIPTION
**Pull request by rukundo-kevin**
### PR Description
- #76 
This pull request introduce the changes that allow the coordinator to add ratings to trainee
### Description of tasks that were expected to be completed
- Add ability to rate trainees
- The integration with the frontend is working
### How has this been tested?
- Run ( npm run dev on the front-end and backend )
- Login an organization ( ex: andela) in the browser
- Sign in a coordinator ( ex: coordinator@devpulse.co , password: Andela123)
- navigate to trainee, add trainee in the cohort , refer to this image
- 
Screen Shot 2022-10-12 at 09 53 28

- Then navigate to Rating ( Select cohort, click on add ratings, rate the trainee and save ) refer here
- 
Screen Shot 2022-10-12 at 10 56 30
- Next test edit functionality by clicking edit icon in the column of actions, edit the ratings, refer here
- 
Screen Shot 2022-10-12 at 11 06 03

- logout the coordinator,  Login admin (ex: admin@devpulse.co, password: Andela123), 
- check on update ratings from sidebar, refer here
- 
Screen Shot 2022-10-12 at 11 11 15
- approve or reject the updates
- Logout the admin and login trainee to check his/her ratings( i.e login trainee with ratings), check performance refer here
- 
Screen Shot 2022-10-12 at 11 15 45

- Click on details to view remarks given on the performance, refer here
- 
Screen Shot 2022-10-12 at 11 17 18

### CODE REVIEW

**Comment by feyton** [comment]
I deployed a review app for you to try out this pull request 👇🏽

Heroku App: https://devpulse-review-app-86.herokuapp.com/


<hidden purpose="for-rewritable-pr-comment-action-use" value="Deploy"></hidden>

**Review by chanceDira — CHANGES_REQUESTED** [review]
Good work @rukundo-kevin,
Just a few issues.

- Am getting the below error on my end.
- Remove log messages.

Screen Shot 2022-09-19 at 08 43 32

**Review by chanceDira — APPROVED** [review]

**Review by Dev-nkundineza — APPROVED** [review]

**Review by alicepretty — APPROVED** [review]

**Review by Himbaza123h — APPROVED** [review]

**Review by alaintresor — APPROVED** [review]

**Review by ceelogre — DISMISSED** [review]
Unable to view any trainees by signing in as a coordinator. Is there an action to do before one can see trainees? Are there no seed data one can use to quickly use?

image

There are unannounced error messages
a rate

**Comment by Dev-nkundineza** [comment]
These errors are due to that The PR for the backend is not merged / deployed . That's why it's throwing such errors

**Review by elissaihimbazwe — CHANGES_REQUESTED** [review]
The COVERAGE DECREASED (-3.007%) TO 71.197% we need to help each other and try to increase it .

**Review by elissaihimbazwe — COMMENTED** [review]
still have COVERAGE DECREASED (-2.4%), let's have a call and see what we can do.

**Review by elissaihimbazwe — APPROVED** [review]

**Review by Julienish14 — APPROVED** [review]

**Review by ceelogre — APPROVED** [review]

**Pull request merged**
