### PR TITLE
#DP-72 feat: internationalization

### PR DESCRIPTION
**Pull request by samyshyaka**
#### What does this PR do?
implement the settings page

#### Description of the tasks to be completed
- [x] The user is able to select and change the language
- [x] Pages are fully translated

#### How should this be manually tested?
```js
git checkout ft-internationalization-dp-72
git fetch
npm install
npm run dev
open http://localhost:3000
```
#### Pre-requisites:

- Clone the project

#### Relevant trello story:
[#DP-72](https://trello.com/c/4LzZZbAn/72-internationalization)

### CODE REVIEW

**Comment by feyton** [comment]
I deployed a review app for you to try out this pull request 👇🏽

Heroku App: https://devpulse-review-app-38.herokuapp.com/


<hidden purpose="for-rewritable-pr-comment-action-use" value="Deploy"></hidden>

**Review by jeandamascyifuzo — CHANGES_REQUESTED** [review]
Good job @samyshyaka 
Can you add a screenshot to compare your result to mine

**Review by chanceDira — COMMENTED** [review]
Good work,

As we are working on translating other pages. you can give us a bonus on this component. I think it is not translated :). #NotFound

Screen Shot 2022-07-21 at 11 48 20

**Comment by samyshyaka** [comment]
> Good work,
> 
> As we are working on translating other pages. you can give us a bonus on this component. I think it is not translated :). #NotFound
> 
> Screen Shot 2022-07-21 at 11 48 20

This is already translated, it's just a small change I need to make for the translations to be applied to the page. Thanks!

**Review by jeandamascyifuzo — APPROVED** [review]

**Review by chanceDira — APPROVED** [review]

**Review by ceelogre — APPROVED** [review]

**Review by IIshimwe — APPROVED** [review]

**Pull request merged**
