### PR TITLE
Fix-close modals after actions

### PR DESCRIPTION
**Pull request by Cynthia-kam**
# PR Description

closes the modals after an action is done.

# Description of tasks that were expected to be completed

Closing the modal when cohort is added.
Closing the modal when a trainee is added
Closing a modal when a trainee is dropped

# Screenshots (If appropriate)

# Please check this Checklist before you submit your PR:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My code generate no warnings
- [ ] My test coverage meet the set test coverage threshold
- [ ] There are no vulnerabilities
- [ ] There are no conflicts with the base branch

### CODE REVIEW

**Review by NdatimanaSamuel — APPROVED** [review]

**Review by ceelogre — APPROVED** [review]
Checked and. approved

**Review by Virgile1k — APPROVED** [review]
checked

**Review by nili-alu — APPROVED** [review]
good

**Review by ceelogre — COMMENTED** [review]
You don't have a backend deployment. How was this reviewed?
image

**Review by ceelogre — CHANGES_REQUESTED** [review]
The list order could be improved.
image

We want something like this:
image
Each icon has should a text next to it describing what it does in a drop-down order.

**Comment by ceelogre** [comment]
Once you click on an item, the dropdown menu should close immediately. Also, clicking anywhere on the screen should close it too.
image

**Review by ceelogre — APPROVED** [review]

**Pull request merged**
