### PR TITLE
#133 Login page revamp 

### LINKED ISSUE #133: Login page revamp
# Description

After a user has provided the name of the org they want to login to, the login name should be `Welcome to org-name` instead of `Welcome back`
Also, once a user logs in, they should not be taken back to the org on logout instead, there should be a `Switch org` option in case they need to use one.
image

### LINKED ISSUE #140: Bugs with programs and cohorts
# Description

After adding a new cohort, if one attempts to add another cohort. The previous data is displayed in the modal.

https://user-images.githubusercontent.com/5022823/196009515-f36301b0-ac16-49c7-a565-28db77e30c8d.mov

Pagination updates properly on component reload. For example, if it's set to show 3 items and you add the fourth, you'll see 4 and have to reload the component for the fourth row to be moved to the second page.

Also, when a user logs out, they are taken to the org login page; ideally this shouldn't be the case  because we are already sure they belong an org so they should be redirected to the login page.]

### PR DESCRIPTION
**Pull request by alaintresor**
# PR Description

Fix #133 

# Description of tasks that were expected to be completed

List all the tasks and sub-tasks that were assigned to you or that you assigned yourself. Make sure you check evey completed task.

# How has this been tested?

Login  organization and you can find the switch org option
logout you will be redirected to `users/login`

# Number of Commits

1 commit

# Screenshots (If appropriate)
Screenshot (7)

# Please check this Checklist before you submit your PR:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My code generate no warnings
- [x] My test coverage meet the set test coverage threshold
- [x] There are no vulnerabilities
- [x] There are no conflicts with the base branch

### CODE REVIEW

**Comment by elissaihimbazwe** [comment]
I deployed a review app for you to try out this pull request 👇🏽
Heroku App: https://devpulse-review-app-164.herokuapp.com/


<hidden purpose="for-rewritable-pr-comment-action-use" value="Deploy"></hidden>

**Review by Placide123 — APPROVED** [review]

**Review by alicepretty — COMMENTED** [review]
looks good on me.

**Review by alicepretty — APPROVED** [review]

**Review by Francoise02 — APPROVED** [review]
This looks good @alaintresor

**Review by ceelogre — CHANGES_REQUESTED** [review]
I'm unable to create a new Organization to test the feature of switching organization. Try and let me know: https://devpulse-review-app-164.herokuapp.com/signup/org

**Comment by alaintresor** [comment]
> I'm unable to create a new Organization to test the feature of switching organization. Try and let me know: https://devpulse-review-app-164.herokuapp.com/signup/org

The issue is not only on my PR even on staging it is not working

**Review by Julienish14 — APPROVED** [review]

**Review by ceelogre — APPROVED** [review]

**Pull request merged**
