### PR TITLE
integrated BE with FE on user registration and user invite

### PR DESCRIPTION
**Pull request by PatrickTUy**
# PR Description
This PR implemented the user registration functionality and addressed requested changes on managing students in a cohort.
# Description of tasks that were expected to be completed

- [x] user registration
- [x] invitation to register
- [x]  email once trainee is added to cohort
- [x] dynamically managing students as opposed to the previous that was accessed by a coordinator
- [x] drop down of users while adding trainee in a cohort instead of typing their email

# How has this been tested?

-    firstly head to this backend PR [link](https://github.com/atlp-rwanda/atlp-pulse-bn/pull/34) and follow the instructions. 
-    git clone 
-    git checkout registering-user-integration
-    npm install  &&  npm run dev 
-  open a new tab in your web browser paste : http://localhost:3000/
N.B  make sure the backend branch is also running

   Below is a list to test the backend PR it will be connected to

-    Head to the sign in button and click on  sign up , fill in the form with a real email address as it will be sent an email.
-  Now head to the sign-in button again and login organization 1 as organization, login a coordinator with the credentials: email:coordinator@pulse.com
password: Andela123
then head to the trainee section on the side bar, click the add button, you will see the email of the new created user in the drop down, select it and choose the cohort in the drop down, now click save, you will see the new added trainee reflected in the table.
- Check in the inbox of the email you've used to create an account

  Repeat the same process and login another user using organization 1 with credentials 
  email:admin@pulse.com
  password: Andela123
  
  Now head to the trainee section on the sidebar, you will find that there are now two buttons add and invite .
  register another user and follow the same process followed by the coordinator  to add them in the cohort.
  You can also invite a user by clicking on the invite button, type a valid email click invite then check its inbox
  

# Number of Commits
1
# Screenshots (If appropriate)
# Please check this Checklist before you submit your PR:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My code generate no warnings
- [x] My test coverage meet the set test coverage threshold
- [x] There are no vulnerabilities
- [x] There are no conflicts with the base branch

### CODE REVIEW

**Comment by Procech20** [comment]
I deployed a review app for you to try out this pull request 👇🏽

Heroku App: https://devpulse-review-app-124.herokuapp.com/


<hidden purpose="for-rewritable-pr-comment-action-use" value="Deploy"></hidden>

**Review by alicepretty — APPROVED** [review]

**Review by Dev-nkundineza — COMMENTED** [review]
I am not able to get trainee, is this registering new trainee or its adding existing trainee in cohort ?
Screen Shot 2022-10-06 at 14 33 02

**Review by Dev-nkundineza — APPROVED** [review]

**Comment by PatrickTUy** [comment]
> I am not able to get trainee, is this registering new trainee or its adding existing trainee in cohort ? Screen Shot 2022-10-06 at 14 33 02

What was remaining was creating a new user and they could be reflected in the drop down.

**Review by Tsa2341 — APPROVED** [review]
Nice work Patrick!

**Review by ceelogre — CHANGES_REQUESTED** [review]
I'm unable to receive email after signup. Also, since this is a signup, we can have a confirm email field.
sign up repeat




These errors are not appropriate for users.
a eror

**Comment by PatrickTUy** [comment]
> I'm unable to receive email after signup. Also, since this is a signup, we can have a confirm email field. sign up repeat
> 
> These errors are not appropriate for users. a eror

The user receives an email after a coordinator adds him in a cohort, the email then contains the organization the user will use while loggin in

**Review by ceelogre — CHANGES_REQUESTED** [review]
Unable to login as coordinator.
image

**Comment by PatrickTUy** [comment]
> Unable to login as coordinator. image

Does the toast show some errors?

**Review by ceelogre — APPROVED** [review]

**Pull request merged**
