### PR TITLE
#DP-60 Ft: Profile Page

### PR DESCRIPTION
**Pull request by rukundo-kevin**
# PR Description
Profile Page
# Description of tasks that were expected to be completed

1.  users are able view their profiles.
2. users are able to edit their profiles

# functionality 

- Sign in with an email e.g(admin@random.com) through this [link]( https://devpulse-review-app-50.herokuapp.com/), use any characters of your choice as password 
- Navigate to setting and click change on the right of Profile section
- Click edit profile to edit the profile.

# Screenshots (If appropriate)
Screen Shot 2022-08-16 at 08 30 31
Screen Shot 2022-08-16 at 08 34 19

# Please check this Checklist before you submit your PR:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My code generate no warnings
- [x] My test coverage meet the set test coverage threshold
- [] There are no vulnerabilities
- [x] There are no conflicts with the base branch

### CODE REVIEW

**Review by chanceDira — COMMENTED** [review]
This is really good, 

I would recommend something like to have a back button while you are on the edit profile.

**Review by jeandamascyifuzo — CHANGES_REQUESTED** [review]
Nice job @rukundo-kevin 
kindly work on the following:
Validate input field
fix the edit icon when you scroll up
Screen Shot 2022-08-16 at 19 55 31
Screen Shot 2022-08-16 at 19 53 56
is it possible to add this functionality in the header where the profile pic is??

**Review by chanceDira — APPROVED** [review]
Nice work @rukundo-kevin

**Review by PatrickTUy — CHANGES_REQUESTED** [review]
Nice work @rukundo-kevin 
Sometimes the user might have made a typo when filling his profile and might want to change a little on the details provided, filling in the form with the details that he/she had initially filled could be a better approach instead of letting the user type out all of the details , while they were just correcting a typo.

**Review by PatrickTUy — CHANGES_REQUESTED** [review]
Nice work @rukundo-kevin 
Sometimes the user might have made a typo when filling his profile and might want to change a little on the details provided, filling in the form with the details that he/she had initially filled could be a better approach instead of letting the user type out all of the details , while they were just correcting a typo.

**Review by Tsa2341 — CHANGES_REQUESTED** [review]
DO solve this overflow
Screenshot (84)

**Review by jeandamascyifuzo — APPROVED** [review]
well done

**Review by Tsa2341 — APPROVED** [review]

**Review by PatrickTUy — APPROVED** [review]
Approved

**Review by ceelogre — COMMENTED** [review]
Content of the right pane should not be very close to the separator line. Add some padding.
image

**Review by ceelogre — APPROVED** [review]

**Pull request merged**
