### PR TITLE
 Bug(fix): Fix Pagination

### LINKED ISSUE #105: fix pagination
when the user sets pagination to more than 10 elements on the table, the buttons of setting pagination disappear whereas they should still be visible

### PR DESCRIPTION
**Pull request by alicepretty**
# PR Description
Fixing pagination functionality
# Description of tasks that were expected to be completed
there should be controls/buttons that allows users to move from one page to another
There is showrooms with different number of train in the table 
# How has this been tested?

1. git clone https://github.com/atlp-rwanda/atlp-pulse-fn
2. checkout to my branch fix-pagination-105
3. npm run dev 
4. You go to Dashboard ,then to the Trainee table .
# Number of Commits
N/A
# Screenshots (If appropriate)
Screen Shot 2022-10-03 at 22 01 24
pagination
pagination 3

### CODE REVIEW

**Comment by Procech20** [comment]
I deployed a review app for you to try out this pull request 👇🏽

Heroku App: https://devpulse-review-app-113.herokuapp.com/


<hidden purpose="for-rewritable-pr-comment-action-use" value="Deploy"></hidden>

**Comment by Procech20** [comment]
The build is failing and as I can see some files are not well rebased, please review your test/snapshot files to resolve the issues and make sure the build passes

**Review by Procech20 — APPROVED** [review]
Page numbers can be seen and selected, as well as the number of data to show on page. Good job on that @alicepretty

**Review by Dev-nkundineza — APPROVED** [review]
Good work @alicepretty

**Review by Himbaza123h — APPROVED** [review]
Yeap

**Review by ceelogre — CHANGES_REQUESTED** [review]
Work with Prophete to fix the deployed app.
image

**Review by ceelogre — APPROVED** [review]

**Pull request merged**
