### PR TITLE
fix programs and cohorts

### PR DESCRIPTION
**Pull request by Tsa2341**
# PR Description

This pr integrates fixes on programs and cohorts.

# Description of tasks that were expected to be completed

- [x] fix dropdowns for users selection
- [x] add update and delete of programs and cohorts
- [x] format dates in tables
- [x] add validation for dates
- [x] fix space between the two words on the modals' title

# How has this been tested?

Follow the process to open and run the program on this [Backend](https://github.com/atlp-rwanda/atlp-pulse-bn/pull/33) PR.

after :
  git clone https://github.com/atlp-rwanda/atlp-pulse-fn.git
  cd atlp-pulse-fn
  git checkout fix/programs-and-cohorts
  npm i
  npm run dev

after :
  Open the program in the browser and log in the organization and the platform as an admin. Create, update, and delete a 
  program or cohort checking that all fixes mentioned above were implemented correctly.

# Number of Commits

1

# Please check this Checklist before you submit your PR:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My code generate no warnings
- [x] My test coverage meet the set test coverage threshold
- [x] There are no vulnerabilities
- [x] There are no conflicts with the base branch

### CODE REVIEW

**Comment by Procech20** [comment]
I deployed a review app for you to try out this pull request 👇🏽

Heroku App: https://devpulse-review-app-121.herokuapp.com/


<hidden purpose="for-rewritable-pr-comment-action-use" value="Deploy"></hidden>

**Review by PatrickTUy — APPROVED** [review]
Approved

**Review by PatrickTUy — APPROVED** [review]
Approved

**Review by Procech20 — COMMENTED** [review]
@Tsa2341 What emails are we supposed to see on this dropdown? Do we create them or they should already be existing? Because am getting no options!
prog cohorts PR

**Review by Dev-nkundineza — APPROVED** [review]

**Review by Procech20 — APPROVED** [review]

**Review by alaintresor — APPROVED** [review]

**Review by Himbaza123h — APPROVED** [review]

**Review by ceelogre — CHANGES_REQUESTED** [review]
Coverage is low.

**Review by elissaihimbazwe — DISMISSED** [review]
The COVERAGE DECREASED (-2.5%) TO 73.92%,  we need to help each other and try to increase it again

**Review by ceelogre — CHANGES_REQUESTED** [review]
Unable to login to Andela org
image

**Review by ceelogre — APPROVED** [review]

**Pull request merged**
