### PR TITLE
#417 Add Bulk Rating

### PR DESCRIPTION
**Pull request by shema-surge**
# PR Description

This PR implements bulk rating of multiple users using a file

# Description of tasks that were expected to be completed

1. Bulk Rating
2. Downloading Rating Template file for a selected team

# Screenshots (If appropriate)

20241028-190815Z-screenshot
20241028-190822Z-screenshot

# Please check this Checklist before you submit your PR:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My code generate no warnings
- [ ] My test coverage meet the set test coverage threshold
- [ ] There are no vulnerabilities
- [ ] There are no conflicts with the base branch

### CODE REVIEW

**Review by JacquelineTuyisenge — APPROVED** [review]

**Review by RWEMAREMY — APPROVED** [review]
Good job

**Review by musabehonore — APPROVED** [review]

**Review by Bananayosostene — APPROVED** [review]

**Review by Tuyisenge2 — APPROVED** [review]

**Comment by Salim-54** [comment]
Check the details of the Test runs and resolve it 
image

**Review by ceelogre — COMMENTED** [review]
How  comes you're able to rate sprint 3 for the whole cohort
image

yet some trainees only have ratings for sprint 1
image

**Review by RWEMAREMY — COMMENTED** [review]
Good job

**Pull request merged**
