### PR TITLE
fix profile  issue integration

### LINKED ISSUE #94: Profile picture update
The user should be able to update their profile picture

### PR DESCRIPTION
**Pull request by PatrickTUy**
# PR Description
This PR integrated the backend with the frontend regarding the bug on profile fetching .
# Description of tasks that were expected to be completed
Fix profile issue
# How has this been tested?
open this [link ](https://devpulse-review-app-135.herokuapp.com/users/login)in your browser
Login in any seeded user e.g( admin@devpulse.co, coordinator@devpulse.co) using organization **Andela,** go to settings in the profile section their profile will have necessary info namely their names
Create a user and login a coordinator or admin to add them into a cohort once done 
Login that new user, go to settings in the profile section and update their profile, It will reflect the changes made.
After testing checkout the backend [PR ](https://github.com/atlp-rwanda/atlp-pulse-bn/pull/40)the review app is connected to.

# Number of Commits
1
# Screenshots (If appropriate)
N/A
# Please check this Checklist before you submit your PR:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My code generate no warnings
- [x] My test coverage meet the set test coverage threshold
- [x] There are no vulnerabilities
- [x] There are no conflicts with the base branch

### CODE REVIEW

**Comment by Procech20** [comment]
I deployed a review app for you to try out this pull request 👇🏽

Heroku App: https://devpulse-review-app-135.herokuapp.com/


<hidden purpose="for-rewritable-pr-comment-action-use" value="Deploy"></hidden>

**Review by Placide123 — APPROVED** [review]

**Review by elissaihimbazwe — APPROVED** [review]

**Review by Himbaza123h — APPROVED** [review]

**Review by ceelogre — CHANGES_REQUESTED** [review]
Unable to login to Andela org due to wrong hyperlink: https://devpulse-review-app-135.herokuapp.com/login/org/users/login

**Comment by PatrickTUy** [comment]
> Unable to login to Andela org due to wrong hyperlink: https://devpulse-review-app-135.herokuapp.com/login/org/users/login

It has been solved

**Review by ceelogre — CHANGES_REQUESTED** [review]
I decided to add an existing trainee instead of inviting a new one. It doesn't work, check the screenshot below.
image

**Comment by PatrickTUy** [comment]
> I decided to add an existing trainee instead of inviting a new one. It doesn't work, check the screenshot below. image

It's because the seeded email was supposed to be a private email but it is not, I've changed the email.

**Review by ceelogre — APPROVED** [review]

**Pull request merged**
