### PR TITLE
ft-tickets-crud that was introduced in issues 242

### PR DESCRIPTION
**Pull request by amiparadis250**
### PR Description
This PR implements CRUD operations for ticket management. It includes the creation, retrieval, update, and deletion of tickets, as well as necessary GraphQL resolvers and mutations.

### Description of tasks that were expected to be completed
- [x] Implemented GraphQL resolvers for CRUD operations on tickets.
- [x] Added `createTicket`, `getAllTickets`, `updateTicket`, and `deleteTicket` `replyToTicket`,  `closeTicket` , mutations.
- [x] Integrated ticket creation and update functionality with push notifications.
- [x] Added access control checks based on user roles.
- [x] Updated ticket status and validation logic.
- [x] Ensured proper error handling and response messages.

### Functionality
- Clone the repository.
- `git checkout ft-tickets-crud-#242`
- Install dependencies with `npm install`.
- Start the development server with `npm run dev`.
- Test the ticket CRUD operations using GraphQL Playground or Postman.

### How has this been tested?
- Tested the creation, retrieval, updating, and deletion of tickets using GraphQL queries and mutations.
- Verified access control and role-based restrictions.
- Checked error handling and response messages for various scenarios.

### PR Checklist:
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My code generates no warnings.
- [x] My test coverage meets the set test coverage threshold.
- [x] There are no vulnerabilities.
- [x] There are no conflicts with the base branch.

### CODE REVIEW

**Review by MugemaneBertin2001 — APPROVED** [review]
LGTM

**Review by pacifiquemboni — APPROVED** [review]

**Review by MugemaneBertin2001 — APPROVED** [review]
LGTM

**Review by elijahladdie — APPROVED** [review]

**Review by Calebgisa72 — APPROVED** [review]

**Review by aimedivin — APPROVED** [review]

**Review by aimedivin — CHANGES_REQUESTED** [review]
@amiparadis250 , @MugemaneBertin2001 this button for `New Tickets` displays on TTL side but  adding ticket does not work please make sure TTL can also add new ticket .

image

**Comment by amiparadis250** [comment]
> @amiparadis250 , @MugemaneBertin2001 this button for `New Tickets` displays on TTL side but adding ticket does not work please make sure TTL can also add new ticket .
> 
> image


@aimedivin  it is fixed now

**Review by aimedivin — APPROVED** [review]

**Pull request merged**
