### PR TITLE
Fix: product-page

### LINKED ISSUE #114: Product should not return 404
# Description
Let's have our product page return a coming soon poster instead of a 404

image

### PR DESCRIPTION
**Pull request by Placide123**
# PR Description
  Design a coming soon page.
# Description of tasks that were expected to be completed
 A user when he/she product on product , it will bring coming soon page
# How has this been tested?
 - go on homepage
 - press on product
# Number of Commits
  PR has 1 commit.
# Screenshots (If appropriate)
Screen Shot 2022-10-05 at 09 18 23

# Please check this Checklist before you submit your PR:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My code generate no warnings
- [ ] My test coverage meet the set test coverage threshold
- [ ] There are no vulnerabilities
- [ ] There are no conflicts with the base branch

### CODE REVIEW

**Comment by Procech20** [comment]
I deployed a review app for you to try out this pull request 👇🏽

Heroku App: https://devpulse-review-app-128.herokuapp.com/


<hidden purpose="for-rewritable-pr-comment-action-use" value="Deploy"></hidden>

**Review by elissaihimbazwe — COMMENTED** [review]
It looks fine .

**Review by elissaihimbazwe — APPROVED** [review]

**Review by Procech20 — APPROVED** [review]
Page looks fine.

**Review by Himbaza123h — APPROVED** [review]
Great!

**Review by ceelogre — APPROVED** [review]

**Pull request merged**
