### PR TITLE
DP-78 Fix error/404 page

### PR DESCRIPTION
**Pull request by IIshimwe**
# PR Description
This PR is for an error page redesigned and re-implemented for various screens. When a client tries to access a page that does not exist, the system will immediately display an error with the reasons and allow the user to return home.
# Description of tasks that were expected to be completed
- [x] Unexpected/unavailable URL display error page with reasons why that happened
- [x] Well displayed on all screens large/medium/small screens
- [x] Have a navbar in order to access other pages
- [x] Having a foot on it in order to access other pages
- [x] Having a background of an image

# How has this been tested?
git clone https://github.com/atlp-rwanda/atlp-pulse-fn.git
cd atlp-pulse-fn
git checkout fix-404-page
npm install
npm run dev

# Screenshots (If appropriate)
**Large Screens**
errorDesktop

**Medium Screens**
errorTablet

**Small Screens**
errorMobile

### CODE REVIEW

**Comment by feyton** [comment]
I deployed a review app for you to try out this pull request 👇🏽

Heroku App: https://devpulse-review-app-58.herokuapp.com/


<hidden purpose="for-rewritable-pr-comment-action-use" value="Deploy"></hidden>

**Review by feyton — CHANGES_REQUESTED** [review]
Can you elaborate on the why we have so many files changed.

I can guess that its about the formatter that may cause issue, but in some files there is dramatic changes.

Rebase so that we get an idea on which changes you have implemented.

**Comment by IIshimwe** [comment]
@feyton I did rebase and about those files changed I didn't touch on them I don't why it showing all those files changed. I only touched on the ones I needed which are the ones for translation.

**Review by chanceDira — COMMENTED** [review]
Good job @IIshimwe,
The redirection is working fine. just resolve the build issue which is failing.

**Review by chanceDira — APPROVED** [review]

**Review by jeandamascyifuzo — APPROVED** [review]
Well done @IIshimwe

**Review by PatrickTUy — APPROVED** [review]
Approved

**Review by ceelogre — CHANGES_REQUESTED** [review]
Whenever I click the review link for the first time, it doesn't load. I need to reload the page for it to work. Use private browsing to test it.
404 review

**Comment by IIshimwe** [comment]
@ceelogre  I don't know what is happening on your end but I and some of my teammates I have reached out to are not getting that issue.

**Comment by feyton** [comment]
> Whenever I click the review link for the first time, it doesn't load. I need to reload the page for it to work. Use private browsing to test it. 404 review

The issue happens frequently but it hard to reproduce as it caused by the large size of the `JS` file being loaded from the server. When you have opened the link before, it loads from the cache and the website loads fast. This is s general downside of react client side rendering since all script  are loaded and executed to the client browser. The main cause of the issue is 

- Poor internet connectivity
- Server side low memory to handle request and data stream (Heroku hobby tier provide low disk speed and RAM)

The issue is not prevalent and can be mitigated by code splitting to avoid loading everything in one go. As I believe the skeleton UI is loaded very fast.

CC: @ceelogre

**Review by ceelogre — APPROVED** [review]

**Pull request merged**
