### PR TITLE
#DP-73 feat: User roles and permissions in UI rendering

### PR DESCRIPTION
**Pull request by feyton**
### What the PR does:
This Pull request add core functionalities related to user identification as well as permission management.
- A user is able to login
- A user is assigned a role based on email they used **(admin@me.com, coordinator@gmail.com)**
- The private routes functionality has been implemented where to access some routes you will need to login first

### Background context
Managing roles and permissions on a front-end application is not full 100% error proof. This PR exposes two core components that are wrapped around `React children`.
#### 1. PrivateRoute:
Used to check if the user is logged in. If the user is stored in local-storage, the component will render the children forwarding all props, otherwise it redirects to the **`Login Page`** with the page the user was trying to visit. 

#### 2. CheckRole:
A component wrapper that takes a **required** prop of `roles`(A list of user types that are allowed to view the children component.

### Additional information
- The state are handled with `React Context` to maintain a single source of truth about the state of the authenticated user
- Apart from the two components, there is a new component called **Tool-tip** which add a message to the icon and help improve the user experience
- The UI will adapt to the authentication state, i.e when a user logs in, the texts will change and routes to adapt to the user.

### How can this be manually tested.
Since currently we have small number of contents designed for different users. I will be adding some pages to demonstrate the functionalities. For now, you can use the **review app** attached to this PR and login with different accounts to see the functionality and see how you can integrate this into your work.
### Associated Trello Cards
[DP-73](https://trello.com/c/XT4yfXRD)

#### Accepted user types:
- `super@anyemail.com` => **super-admin**
- - `admin@anyemail.com` => **admin**
- `trainee@anymail.com` => **trainee**
- `coordinator@anymail.com` => **coordinator**
- `user@anymail.com` => **user**

> All you have to do is click the **Sign in ** button and press continue. Use any of the above emails (**Based on your target userType**), and any `non-empty` password. Then sign-in, you will be redirected to the dashboard and based o your user type, you may find the UI changed.

Thank you.

### CODE REVIEW

**Comment by feyton** [comment]
I deployed a review app for you to try out this pull request 👇🏽

Heroku App: https://devpulse-review-app-30.herokuapp.com/


<hidden purpose="for-rewritable-pr-comment-action-use" value="Deploy"></hidden>

**Review by samyshyaka — DISMISSED** [review]
Currently, when you login using the admin email, you are directed to the super-admin dashboard. I think we need a super-admin role different from the admin role.

**Review by ceelogre — DISMISSED** [review]
Change the PR label and fix failing builds.

**Review by chanceDira — APPROVED** [review]
Good work 👍 @feyton

**Review by samyshyaka — APPROVED** [review]

**Review by samyshyaka — DISMISSED** [review]
Find the reason why the pull request build is failing

**Review by ceelogre — COMMENTED** [review]
Please first raise the coverage.

**Review by jeandamascyifuzo — APPROVED** [review]
Great job @feyton

**Review by ceelogre — COMMENTED** [review]
What Trello card is associated with this task?

**Comment by feyton** [comment]
> What Trello card is associated with this task?

There is no card, but am happy to add one with the tasks checklist if acceptable

**Comment by ceelogre** [comment]
> > What Trello card is associated with this task?
> 
> There is no card, but am happy to add one with the tasks checklist if acceptable @ceelogre

Yes please! add it, then we can go ahead and merge.

**Comment by feyton** [comment]
> > > What Trello card is associated with this task?
> > 
> > 
> > There is no card, but am happy to add one with the tasks checklist if acceptable @ceelogre
> 
> Yes please! add it, then we can go ahead and merge.

@ceelogre The card has been added [#DP-73](https://trello.com/c/XT4yfXRD)

**Review by ceelogre — APPROVED** [review]

**Pull request merged**
