### PR TITLE
Fix: UI-Design for siginin page

### LINKED ISSUE #116: Signin has a large register component
# Description

The signin page has a register section that overshadows it. Let's remove it and have a smaller register section at the same time centering the signin section.
asignin

### PR DESCRIPTION
**Pull request by elissaihimbazwe**
# PR Description
This RP fixes the UI design for the login page 

# Description of tasks that were expected to be completed

1. Removing the Registration section on the sign-in page
2. Making the sign-in inputs visible
3. Making a sign in button clear and focused

# How has this been tested?

1. Clone this Branch
2. Install necessary dependencies
3. Run the branch with the command `npm run dev`
4. Go to sign in page and test the above tasks completed as described above

# Number of Commits
1 commit
# Screenshots (If appropriate)
Screen Shot 2022-09-29 at 20 21 09

# Please check this Checklist before you submit your PR:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My code generate no warnings
- [x] My test coverage meet the set test coverage threshold
- [x] There are no vulnerabilities
- [x] There are no conflicts with the base branch

### CODE REVIEW

**Comment by Procech20** [comment]
I deployed a review app for you to try out this pull request 👇🏽

Heroku App: https://devpulse-review-app-118.herokuapp.com/


<hidden purpose="for-rewritable-pr-comment-action-use" value="Deploy"></hidden>

**Comment by ElissaDesign** [comment]
> I deployed a review app for you to try out this pull request 👇🏽
> 
> Heroku App: https://devpulse-review-app-118.herokuapp.com/

Ok lemme check

**Review by Procech20 — APPROVED** [review]
The page looks fine and responsive.

**Review by Himbaza123h — APPROVED** [review]

**Review by PatrickTUy — CHANGES_REQUESTED** [review]
Good work @ElissaDesign since you've worked on this, can you apply the same shadow to the organization sign to make it look better
Screen Shot 2022-10-03 at 12 27 43

**Comment by ElissaDesign** [comment]
> Good work @ElissaDesign since you've worked on this, can you apply the same shadow to the organization sign to make it look better Screen Shot 2022-10-03 at 12 27 43

Thanks @PatrickTUy , lemme work on that also .

**Review by ceelogre — COMMENTED** [review]
What's the status of Patrick's comment?

**Comment by ElissaDesign** [comment]
> Good work @ElissaDesign since you've worked on this, can you apply the same shadow to the organization sign to make it look better Screen Shot 2022-10-03 at 12 27 43

@PatrickTUy , how is it? finished implementing the shadow and small rounded on the organization page
Screen Shot 2022-10-05 at 10 03 16

**Review by Himbaza123h — APPROVED** [review]

**Review by PatrickTUy — APPROVED** [review]
Good job @ElissaDesign

**Pull request merged**
