### PR TITLE
#DP-47 feat: Settings page

### PR DESCRIPTION
**Pull request by samyshyaka**
#### What does this PR do?
implement the settings page

#### Description of the tasks to be completed
- [x] The settings page is implemented
- [x] The page is responsive
- [x] The page has both the light and dark mode

#### How should this be manually tested?
```js
git checkout ft-settings-page-dp-47
git fetch
npm install
npm run dev
open http://localhost:3000/dashboard/settings
```
#### Pre-requisites:

- Clone the project

#### Relevant trello story:
[#DP-47](https://trello.com/c/Bstq4ScS/47-settings-page)

### CODE REVIEW

**Comment by feyton** [comment]
I deployed a review app for you to try out this pull request 👇🏽

Heroku App: https://devpulse-review-app-25.herokuapp.com/


<hidden purpose="for-rewritable-pr-comment-action-use" value="Deploy"></hidden>

**Review by feyton — CHANGES_REQUESTED** [review]
### Changes
Hello @samyshyaka , these are great features,though please look into the following issues

- **Coverage** directory in history. Remember to remove the chached version and update the branch
- **Multiple languages support**: When deployed on heroku, the application is built served by `express`, you will need to add the `public` directory into **statics** to make it work. Use the following lines for reference


> The code reference for editing `server.mjs`

```js
// .... up to line 7
// line 8
app.use(expressStatic(join(resolve(), 'dist')));
app.use(expressStatic(join(resolve(), 'public')));
//line 9 ....
```

**Review by feyton — APPROVED** [review]

**Review by chanceDira — APPROVED** [review]
Very nice, working fine. Good job 👍

**Review by ceelogre — CHANGES_REQUESTED** [review]
Looks like you've not been able to set the default value for the theme?
image

**Comment by feyton** [comment]
I deployed a review app for you to try out this pull request 👇🏽

Heroku App: https://devpulse-review-app-25.herokuapp.com/


<hidden purpose="for-rewritable-pr-comment-action-use" value="Deploy"></hidden>

**Comment by samyshyaka** [comment]
> Looks like you've not been able to set the default value for the theme? image

This has now been solved

**Review by ceelogre — COMMENTED** [review]
I'm unable to access the review app.

**Comment by samyshyaka** [comment]
> I'm unable to access the review app.

Can you try again or check if it's not a problem on your end? On my end I can access it.

**Comment by ceelogre** [comment]
The card is not properly centered in the right section.
image

**Comment by feyton** [comment]
I deployed a review app for you to try out this pull request 👇🏽

Heroku App: https://devpulse-review-app-25.herokuapp.com/


<hidden purpose="for-rewritable-pr-comment-action-use" value="Deploy"></hidden>

**Review by ceelogre — CHANGES_REQUESTED** [review]

**Comment by feyton** [comment]
I deployed a review app for you to try out this pull request 👇🏽

Heroku App: https://devpulse-review-app-25.herokuapp.com/


<hidden purpose="for-rewritable-pr-comment-action-use" value="Deploy"></hidden>

**Review by ceelogre — APPROVED** [review]

**Pull request merged**
