### PR TITLE
Bug(fix): Fix CI deployment

### PR DESCRIPTION
**Pull request by Procech20**
# PR Description
Changing staging app address
# Description of tasks that were expected to be completed
- Change app hosting address
- Fix CI deployment
# How has this been tested?
_A new staging application will be deployed from a new account and will be available for use_
# Screenshots (If appropriate)
_N/A_
# Please check this Checklist before you submit your PR:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My code generate no warnings
- [x] My test coverage meet the set test coverage threshold
- [x] There are no vulnerabilities
- [x] There are no conflicts with the base branch

### CODE REVIEW

**Comment by Procech20** [comment]
I deployed a review app for you to try out this pull request 👇🏽

Heroku App: https://devpulse-review-app-112.herokuapp.com/


<hidden purpose="for-rewritable-pr-comment-action-use" value="Deploy"></hidden>

**Review by PatrickTUy — APPROVED** [review]
Approved

**Review by Tsa2341 — APPROVED** [review]

**Review by Himbaza123h — APPROVED** [review]
Good!

**Review by ceelogre — COMMENTED** [review]
I'm unable to login.

a una

**Comment by Procech20** [comment]
Review apps are still making requests to the localhost, I'll fix that.

**Pull request merged**
