### PR TITLE
#477 improving invitation filter

### LINKED ISSUE #477: Improve invitation filters
### Description

- Improve search functionality
- Redesign and implement invitation filters, I suggest using dropdowns for role and status

### PR DESCRIPTION
**Pull request by Ndevu12**
# PR Description

Improving invitation filters on the admin invitation page, where the admin can filter invitations that have invitees with a specific role and invitations with a specific status.

# Description of tasks that were expected to be completed

- Improving invitation filters
- Update both backend and frontend for the best filtering experience

# How has this been tested?

Log in to the application through this https://metron-devpulse-n53rhrvfz-metron.vercel.app/ as an admin using credentials: Email:[devpulse@proton.me](mailto:devpulse@proton.me) and *Password: **Test@12345** * and go to the invitation nav option you will find invitation search there and the filter options, Then you can choose the one to test first.

# Number of Commits

**1 commits**

# Screenshots 

Screenshot 2024-09-13 at 11 25 30

# Please check this Checklist before you submit your PR:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My code generate no warnings
- [x] My test coverage meet the set test coverage threshold
- [x] There are no vulnerabilities
- [x] There are no conflicts with the base branch

### CODE REVIEW

**Review by UwicyezaG — APPROVED** [review]

**Review by YvetteNyibuka — APPROVED** [review]

**Review by niyobertin — COMMENTED** [review]
resolve a conflict

**Review by mpanoathos — APPROVED** [review]

**Review by niyobertin — APPROVED** [review]

**Comment by ncutixavier** [comment]
image
- When you select only TTL, the filter button is disabled
- Select box in dark mode, need improvement on colors

**Comment by Ndevu12** [comment]
> image
> 
> * When you select only TTL, the filter button is disabled
> * Select box in dark mode, need improvement on colors

Yes, the filter button remains disabled when only TTL is selected because we specifically filter invitations by role and status. Enabling it could lead to duplication, as we already have a search bar for retrieving and filtering based on other criteria.

**Comment by Ndevu12** [comment]
@ncutixavier The Select box has been improved.

Screenshot 2024-09-16 at 09 24 06

**Comment by ncutixavier** [comment]
No, That's not how it works. when I select a role or status, we should get data

**Comment by Ndevu12** [comment]
> No, That's not how it works.

But that is what is in the description!


How do you want it to be like?

**Comment by Ndevu12** [comment]
> No, That's not how it works. when I select a role or status, we should get data

What can make it differ from the search bar, if it does that?

Can we have a short call please?

**Comment by Ndevu12** [comment]
All new requirements have been addressed successfully.


Screenshot 2024-09-16 at 12 43 07
Screenshot 2024-09-16 at 12 43 28

**Review by GSinseswa721 — APPROVED** [review]

**Review by ncutixavier — APPROVED** [review]

**Pull request merged**
