### PR TITLE
fix: Improve styling and add fonts

### PR DESCRIPTION
**Pull request by jeandamascyifuzo**
### What the PR does:
- Add new fonts to the application
- Replace the existing fonts
- Deploy a new landing page with a background image

### Fixes

- [x] Side menu not closing when user clicks outside
- [x] Background image not occupying the whole space
- [x] Fix div sizing and improved the responsivenes
- [x] Added the loading skeleton UI for user experience

### Background context
After a review of the application, this PR ship a new iteration that replace the **SVG** as the placeholder but instead add a background image. This is a testing and with team reviews as well as recommendation, the UI will be improved.

### Context
The new fonts are as following and all can be explored on [Google Fonts](https://fonts.google.com)
- Title Text (ex: **Welcome to devpulse*): [`fontFamily: 'Lexend'`](https://fonts.google.com/specimen/Lexend?query=lexend)
- Sub-title and paragraph text (ex: **Navbar title name**): [`fontFamily: 'Poppins'`](https://fonts.google.com/specimen/Poppins?query=poppin)

### Testing
The features need no local testing and can be review on the app created and attached on this Pull Request
image

image

### CODE REVIEW

**Comment by feyton** [comment]
I deployed a review app for you to try out this pull request 👇🏽

Heroku App: https://devpulse-review-app-23.herokuapp.com/


<hidden purpose="for-rewritable-pr-comment-action-use" value="Deploy"></hidden>

**Review by feyton — APPROVED** [review]
This is well implemented @jeandamascyifuzo

**Review by IIshimwe — APPROVED** [review]

**Review by samyshyaka — CHANGES_REQUESTED** [review]
Great job @jeandamascyifuzo, I have some feedback for you.
- Can you make the header completely transparent? When the user scrolls down that's when we can see the usual background colors of the header on the light or dark mode depending on what the user chooses
- I also think that it's best that the footer should only be seen when someone scrolls down.

**Review by ceelogre — COMMENTED** [review]
Let's have a serif font for the home page.

**Comment by feyton** [comment]
> Great job @jeandamascyifuzo, I have some feedback for you.
> 
>     * Can you make the header completely transparent? When the user scrolls down that's when we can see the usual background colors of the header on the light or dark mode depending on what the user chooses
> 
>     * I also think that it's best that the footer should only be seen when someone scrolls down.

Since we have little content, the user does not need to scroll down for some information on the footer since we have some important links that require user attention

On the issue of making the header transparent, that would be great but when I tried, it requires adding a really dark background on the picture to manage all different scenarios. It was not great for user experience and that is one reason I used a semi-transparent background

**Review by ceelogre — CHANGES_REQUESTED** [review]
The new font looks significantly better. Great Job!

The italics part is not consistent, for example why is it that trainees is italized but student is not? Decide which words should be italized. There's also a missing space
image

I'm not sure also where this image would be relevant: https://github.com/atlp-rwanda/atlp-pulse-fn/blob/93369a872badaeb306251e6df1de0d42c34015ae/src/assets/bg-image.png

**Review by ceelogre — COMMENTED** [review]
Builds are failing.

**Pull request merged**
