### PR TITLE
#Ft-39-ticket-system-continued Add Reply Feature on Ticket System

### PR DESCRIPTION
**Pull request by ericndungutse**
# PR description
This PR continues `ticket system` by adding replies capabilities.

# Description of tasks that were expected to be completed

- [x] Reply on ticket
- [x] Resolve Ticket
- [x] Display details of a ticket

# How has this been tested?

- Pull this pr in local machine
- Set **BACKEND_URL** to `https://devpulse-backend-pr-108.onrender.com/`
- Signin and go on `dashboard/support`
- Submit a message
- Sign out and signin as **superadmin**
- Go to `dashboard/ tickets`
- Open one ticket and see its details
- Using the form, submit a reply

### Track PR
Trello Card: [39-ticket-system-continued](https://trello.com/c/hWy3Ov8x/39-ticket-system-continued)

#### Screenshoots

Screenshot (103)

Screenshot (104)

Screenshot (105)

### CODE REVIEW

**Review by oliviertech212 — APPROVED** [review]

**Review by AbdulKhaliq59 — APPROVED** [review]
LGTM

**Review by patsicko — APPROVED** [review]

**Review by ceelogre — DISMISSED** [review]
How do I create a new ticket?
image

**Review by ceelogre — DISMISSED** [review]
A reply box should appear at the bottom not in the middle of a conversation.
image

Updates do not show in real time on the admin page. It requires a page refresh. Is this related to sockets?
image

New tickets don't show up immediately in the superadmin panel.
image

**Review by ceelogre — COMMENTED** [review]
The flow of conversation is not chronological unless you reload the page. Also, why is it that older messages are hidden?
image
image

**Pull request merged**
