### PR TITLE
#315 Fix Input Validation Issue On Coordinator Dashboard

### LINKED ISSUE #315: Input validation
# Description

One is able to submit a form with empty fields.
image

### PR DESCRIPTION
**Pull request by nshutip**
# PR Description

This PR fixes issue 315. It adds the necessary validation rule to ensure that a coordinator is unable to submit a form with empty fields while trying to add a trainee.

# Description of tasks that were expected to be completed

Add input validation rule to make sure form can not be submitted with empty fields.

# How has this been tested?

I tested this by logging into the coordinator dashboard and trying to submit the add trainee form without entering all the information. When I clicked the "Save" button, I received a toast notification telling me to "Enter all the required information".
# Number of Commits

1

# Screenshots (If appropriate)

Screenshot 2023-10-24 at 17 39 58
Screenshot 2023-10-24 at 17 40 09
Screenshot 2023-10-24 at 17 40 24

# Please check this Checklist before you submit your PR:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My code generate no warnings
- [x] My test coverage meet the set test coverage threshold
- [x] There are no vulnerabilities
- [x] There are no conflicts with the base branch

### CODE REVIEW

**Comment by nshutip** [comment]
[Fix input validation issue on the coordinator dashboard.](https://trello.com/c/wydeJVT5/172-fix-input-validation-issue-on-the-coordinator-dashboard)

**Review by Virgile1k — APPROVED** [review]
Checked and approved

**Review by Muhet — APPROVED** [review]
Good

**Review by nili-alu — APPROVED** [review]
good job

**Review by ceelogre — COMMENTED** [review]
image

**Comment by ceelogre** [comment]
Message needs to be translated!
image

**Pull request merged**
