### PR TITLE
fix: Menu close on mobile

### PR DESCRIPTION
**Pull request by Julesbi**
closing menu on mobile devices

# PR Description
This PR solve an issue on closing menu on mobile device
# Description of tasks that were expected to be completed

- [x] Closing menu on mobile device 

# How has this been tested?
Use any user(admin/trainee/superadmin)  credentials to login and inspect small screen, and click on any items on navbar to check if will be closed automatically.
# Number of Commits
1 commit

### CODE REVIEW

**Comment by feyton** [comment]
I deployed a review app for you to try out this pull request 👇🏽

Heroku App: https://devpulse-review-app-59.herokuapp.com/


<hidden purpose="for-rewritable-pr-comment-action-use" value="Deploy"></hidden>

**Review by chanceDira — CHANGES_REQUESTED** [review]
Good job @Julesbi,
However upon choosing another tab like pricing and product there are no components shown.

Refer to this picture.

Screen Shot 2022-08-14 at 11 06 04

**Review by chanceDira — APPROVED** [review]
Good work @Julesbi

**Review by Tsa2341 — APPROVED** [review]

**Review by Tsa2341 — DISMISSED** [review]
Though, Do solve the build errors so that all test passes.

**Review by feyton — APPROVED** [review]
This is well implemented and the menu closes when switching to a new page

**Review by jeandamascyifuzo — APPROVED** [review]

**Review by ceelogre — APPROVED** [review]

**Pull request merged**
