### PR TITLE
Ft trainee dashboard

### PR DESCRIPTION
**Pull request by Luciefifi**
# PR Description

Trainee dashboard re-design

# Description of tasks that were expected to be completed

- [x] Trainee page is re-designed
- [x] page is responsive
- [x] The load time is below 2 seconds

# How has this been tested?
1. locally :
- clone this repo
- open the project in your IDE
- install dependencies by `npm i`
- checkout to `ft-trainee-dashboard`
- start the server by `npm run dev`
- login as a trainee
- if the logged in trainee do not have ratings , please login as coordinator to give some  ratings
- navigate to dashboard

2. Deployed version:
- Visit `https://metron-devpulse-git-ft-trainee-dashboard-metron.vercel.app/`
- login as a trainee
- navigate to dashboard
# Number of Commits

The number of commits should not exceed **2 commits**. In case they are more than that, please take your time and squash them.

# Screenshots (If appropriate)
Screen Shot 2023-08-29 at 07 26 34
Screen Shot 2023-08-29 at 07 27 44
Screen Shot 2023-08-29 at 07 27 51

# Please check this Checklist before you submit your PR:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My code generate no warnings
- [x] My test coverage meet the set test coverage threshold
- [x] There are no vulnerabilities
- [x] There are no conflicts with the base branch

### CODE REVIEW

**Review by AbdulKhaliq59 — CHANGES_REQUESTED** [review]
Check on responsiveness unless you did a great a job
Screenshot 2023-08-16 at 15 18 26

**Review by chrill-christella — APPROVED** [review]

**Review by oliviertech212 — CHANGES_REQUESTED** [review]
image This needs to be fixed instead of displaying this dropdown arrow we can have cohort only or display team phase

**Comment by Luciefifi** [comment]
> image This needs to be fixed instead of displaying this dropdown arrow we can have cohort only or display team phase

I fixed it @oliviertech212 , You may  check again.

**Review by Habihirwe — APPROVED** [review]

**Review by AbdulKhaliq59 — APPROVED** [review]
LGTM

**Comment by oliviertech212** [comment]
image
fix  view comment

**Comment by Luciefifi** [comment]
> image fix view comment
👍

**Review by oliviertech212 — APPROVED** [review]

**Review by ceelogre — CHANGES_REQUESTED** [review]
The dashboard for trainees is not loading.
image

**Review by ceelogre — COMMENTED** [review]
Didn't we say the x axis should start at 1?
image

**Review by ceelogre — APPROVED** [review]

**Pull request merged**
