### PR TITLE
Inviting guests on the calendar

### PR DESCRIPTION
**Pull request by suave990**
# PR Description

Adding the guests to the calender
Sending Emails to guests
Accepting or rejecting the invite (trainee)
Once confirmed, Event shows on everyOne's Calender

# How has this been tested?
Tested locally From Dashboard to Calender and then Add event
Logged in as a coordinator `georgia.gonzales@devpulse.com`
Receive email invite on guest account assigned

# Number of Commits

1

# Screenshots (If appropriate)

# Please check this Checklist before you submit your PR:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My code generate no warnings
- [x] My test coverage meet the set test coverage threshold
- [x] There are no vulnerabilities
- [x] There are no conflicts with the base branch

### CODE REVIEW

**Review by UwaweTera — COMMENTED** [review]
@suave990 inviting user not working check well

**Comment by Luciefifi** [comment]
> @suave990 inviting user not working check well

hey @UwaweTera  can you please check again

**Review by ceelogre — CHANGES_REQUESTED** [review]
The accepting or rejecting link is pointing to localhost.

image

image

**Review by AbdulKhaliq59 — CHANGES_REQUESTED** [review]
I can suggest something to change
 - when someone accept the invitation he/she has to see that event in his/her calendar by using `getAcceptedEvents` resolver on backend
 - another thing is the URL to confirm invitation assume that this is going to be hosted
 - Another is to remove that word `some reason` as default to make it a placeholder
Screenshot 2023-07-14 at 11 30 54

Screenshot 2023-07-14 at 11 28 57

**Comment by blackd44** [comment]
> I can suggest something to change
> 
> * when someone accept the invitation he/she has to see that event in his/her calendar by using `getAcceptedEvents` resolver on backend
> * another thing is the URL to confirm invitation assume that this is going to be hosted
> * Another is to remove that word `some reason` as default to make it a placeholder
> 
> Screenshot 2023-07-14 at 11 30 54 Screenshot 2023-07-14 at 11 28 57

@AbdulKhaliq59 `getAcceptedEvents` was used to get the events
check in codes

**Review by AbdulKhaliq59 — APPROVED** [review]

**Review by UwaweTera — APPROVED** [review]

**Review by ceelogre — CHANGES_REQUESTED** [review]
Your tests coverage has fallen below the threshold.

**Review by ceelogre — CHANGES_REQUESTED** [review]
A user should be able to view details of an event (name, host, guests, ...)
Add deployment url instead of localhost.

**Review by ceelogre — COMMENTED** [review]
Closing this as it's taken over two weeks.

**Comment by ceelogre** [comment]
When a user is not logged in, clicking on accept/reject takes them to login page and after a successful login, they are taken to performance page instead of an accept/reject page. This should be fixed.

Also, how comes email still come from Gmail accounts?
image

**Comment by ceelogre** [comment]
Stale.

**Pull request closed without merging**
