### PR TITLE
DP-109 Fix: Create rating system Integration 

### PR DESCRIPTION
**Pull request by alicepretty**
admin is able to query all rating sytems

# PR Description
This PR is used to integrate the page accessible to an admin where he/she will be able to create rating(grading) systems.
# Description of tasks that were expected to be completed

- [x] Admin is be able to query all rating systems 
- [x] Admin is able to create a rating system

# How has this been tested?

- Sign in as an admin 
- Navigate on grading system using the navbar
- Query rating systems using a dropdown
- Click on custom to add new rating system
- Use a dropdown to check if the addded rating system is there

-Screenshots (If appropriate)

Refer to this image to know how grading system are added.

Screenshot (188)

### CODE REVIEW

**Comment by elissaihimbazwe** [comment]
I deployed a review app for you to try out this pull request 👇🏽
Heroku App: https://devpulse-review-app-160.herokuapp.com/


<hidden purpose="for-rewritable-pr-comment-action-use" value="Deploy"></hidden>

**Review by alaintresor — APPROVED** [review]

**Review by elissaihimbazwe — APPROVED** [review]

**Review by ceelogre — CHANGES_REQUESTED** [review]
Translation is not complete.
image

**Review by Placide123 — APPROVED** [review]

**Comment by ceelogre** [comment]
When an admin login, they should see a list of all existing grading systems.
image

**Comment by alicepretty** [comment]
> When an admin login, they should see a list of all existing grading systems. image

When admin is logged in ,he first see the select box ,when he click on it he will see all existing grading system @ceelogre

**Comment by alicepretty** [comment]
> > When an admin login, they should see a list of all existing grading systems. image
> 
> When admin is logged in ,he first see the select box ,when he click on it he will see all existing grading system @ceelogre

If i get you well , you want if admin login , you want him to see the list of all created grading system immediately . and the way i did that the admin after logged in he will see all those grading system in the select box  
Screen Shot 2022-11-03 at 14 26 49
(this is the list of grading system when the admin click on that select box)




https://user-images.githubusercontent.com/61903976/199750850-c3edcdc1-a0be-48ac-aab1-dc170ee43e81.mov @ceelogre

**Review by ceelogre — APPROVED** [review]

**Pull request merged**
