### PR TITLE
Feature/notifications preference

### PR DESCRIPTION
**Pull request by Munezeroolivierhugue**
# PR Description

Implementation of notification preference

# Description of tasks that were expected to be completed

We should be able to click and change push and email either on or off

# How has this been tested locally?

- Clone [repo](https://github.com/atlp-rwanda/atlp-pulse-fn)
- Change into the directory **atlp-pulse-fn**
- Checkout to the branch: [feature/notifications-preference](https://github.com/atlp-rwanda/atlp-pulse-fn/tree/feature/notifications-preference)
- Run the command `npm install` 
- Run the command `npm run dev`
- Visit ([Visit Preview](https://vercel.live/open-feedback/metron-devpulse-git-feature-notifications-preference-metron.vercel.app?via=pr-comment-visit-preview-link&passThrough=1))
- Login as trainee
- Enable push or email notification in settings
- Login as Coordinator and try give rating for push notification and updating rating for email notificatiom
- Then disable push or email notification and trigger notifications again to see if it's not sent

# Screenshot

Screenshot 2023-07-26 at 17 26 19

### CODE REVIEW

**Review by Mystica52 — COMMENTED** [review]
can you add a screenshot

**Review by oliviertech212 — CHANGES_REQUESTED** [review]
Screenshot 2023-07-27 at 14 11 14
I'm not able to add a trainee

**Review by Luciefifi — APPROVED** [review]

**Review by Luciefifi — APPROVED** [review]

**Review by oliviertech212 — APPROVED** [review]

**Review by ceelogre — CHANGES_REQUESTED** [review]
image

**Comment by ceelogre** [comment]
Putting this on-hold until we fix the email-issue.

**Review by ceelogre — APPROVED** [review]

**Pull request merged**
