### PR TITLE
fixing issues on manage ratings

### PR DESCRIPTION
**Pull request by Dev-nkundineza**
# PR Description
This PR Fixes the issues on manage ratings
Please include a brief description of the pull request you want to raise.
This PR Fixes the issues on manage ratings
# Description of tasks that were expected to be completed

- [x] Manager can see all ratings
- [x] On updated remarks, there is no need for admin approval
- [x] The coordinator has to get an email if there is a rejection/ approval of the  ratings 

List all the tasks and sub-tasks that were assigned to you or that you assigned yourself. Make sure you check every completed task.

# How has this been tested?

- [ ]  Clone frontend repository [frontend](https://github.com/atlp-rwanda/atlp-pulse-fn.git)
- [ ] Clone backend repository [](https://github.com/atlp-rwanda/atlp-pulse-bn.git)
- [ ] checkout the branch   fix-manage-ratings on both frontend and backend 
- [ ] Add the ratings to a trainee
- [ ] Update the Ratings
- [ ] Login as admin, view all ratings

# Number of Commits
1 commit

### CODE REVIEW

**Review by alicepretty — APPROVED** [review]

**Comment by Procech20** [comment]
I deployed a review app for you to try out this pull request 👇🏽
Heroku App: https://devpulse-review-app-144.herokuapp.com/


<hidden purpose="for-rewritable-pr-comment-action-use" value="Deploy"></hidden>

**Review by Procech20 — CHANGES_REQUESTED** [review]
The ratings are shown on admins side but the updated_ratings is saying `missing or expired organization token` please check if you have put it in your variable during the query

**Review by Procech20 — APPROVED** [review]
Kudos @Dev-nkundineza Works fine with good design

**Review by PatrickTUy — APPROVED** [review]
Approved

**Review by ceelogre — CHANGES_REQUESTED** [review]
Unable to login due to wrong signin url after providing org name.

**Comment by Dev-nkundineza** [comment]
> Unable to login due to wrong signin url after providing org name.

Screen Shot 2022-10-24 at 11 40 27
I am able to signin on my end! can you check again

**Review by ceelogre — APPROVED** [review]

**Pull request merged**
