### PR TITLE
ft: Integration for register an organisation

### LINKED ISSUE #87: Register an org
# Description
The frontend for registering an org doesn't seem to be connected to the backend.
image

### PR DESCRIPTION
**Pull request by jeandamascyifuzo**
# PR Description
Integration for registering an organisation

# Description of tasks that were expected to be completed
user should belong in a certain organisation
successful organisation login redirect to login page
appropriate error message

# How has this been tested?
git clone https://github.com/atlp-rwanda/atlp-pulse-fn.git
cd atlp-pulse-fn
git checkout ft-register-org
npm I
npm run dev

also do.
git clone https://github.com/atlp-rwanda/atlp-pulse-bn.git
cd atlp-pulse-bn
git checkout ft-register-org
npm I
npm run seed
npm run dev

after all the apps are running, open `http://localhost:3000`

- request an organization
- login with `organization 1` and continue to login
- login with superAdmin credentials
- go to organization in the sidebar
- and add that organization.

# Screenshots (If appropriate)

### CODE REVIEW

**Comment by feyton** [comment]
I deployed a review app for you to try out this pull request 👇🏽

Heroku App: https://devpulse-review-app-100.herokuapp.com/


<hidden purpose="for-rewritable-pr-comment-action-use" value="Deploy"></hidden>

**Review by Tsa2341 — APPROVED** [review]

**Review by PatrickTUy — APPROVED** [review]
Approved

**Review by kelliaUmuhire — APPROVED** [review]
Looks good.

**Review by Himbaza123h — APPROVED** [review]

**Review by Procech20 — COMMENTED** [review]
Good job @jeandamascyifuzo but since you worked on organization registry, Is it possible to work on that link on the organization login that says: 'Find your organization', so that someone can actually find their organization

**Comment by PatrickTUy** [comment]
> Good job @jeandamascyifuzo but since you worked on organization registry, Is it possible to work on that link on the organization login that says: 'Find your organization', so that someone can actually find their organization

Yes @Procech20, this was implemented, When someone 

> Good job @jeandamascyifuzo but since you worked on organization registry, Is it possible to work on that link on the organization login that says: 'Find your organization', so that someone can actually find their organization

Yes @Procech20, that's a good insight but the PR is all about registering an organisation, may be it will be a different task that might need a different PR.

**Comment by PatrickTUy** [comment]
> Good job @jeandamascyifuzo but since you worked on organization registry, Is it possible to work on that link on the organization login that says: 'Find your organization', so that someone can actually find their organization

Yes @Procech20, this was implemented, When someone 

> Good job @jeandamascyifuzo but since you worked on organization registry, Is it possible to work on that link on the organization login that says: 'Find your organization', so that someone can actually find their organization

Yes @Procech20, that's a good insight but the PR is all about registering an organisation, may be it will be a different task that might need a different PR.

**Review by ceelogre — APPROVED** [review]
I've seen some minor improvements but let's merge this to go fast.

**Pull request merged**
