### PR TITLE
bug fix on profile

### LINKED ISSUE #173: Profile fix
# Description
Some of the details in the user profile are hard-coded. Let's get up-to-date info from the backend.

### LINKED ISSUE #246: Profile error
# Description
When opening a profile page, there is an error message.
image

### PR DESCRIPTION
**Pull request by Habihirwe**
**PR Description**

Profile CRUD , this shows the profile of the use who logged in according to his or her role

**Description of tasks that were expected to be completed**

About and organisation tabs are implemented properly 
we removed Account tab because we have find that it is not needed 
also here user see  the profile according to the role he/she is assigned to for example admin, manager, coordinator or trainee

 **How has this been tested?**

clone the repo then run npm install , npm run dev , switch to an organisation you want , login with an role you want and finally go to profile you will be able to see all these tabs 

 **Number of Commits**

1

 **Screenshots (If appropriate)**

Screen Shot 2023-07-14 at 01 29 38
Screen Shot 2023-07-14 at 01 31 50
Screen Shot 2023-07-14 at 01 32 13

### CODE REVIEW

**Review by blackd44 — CHANGES_REQUESTED** [review]
Profile is working well
but when you change profile picture you can read notifications

https://github.com/atlp-rwanda/atlp-pulse-fn/assets/112763782/6451b6a8-03b2-491d-b3b9-52034481b82b

Screenshot 2023-07-22 at 00 32 53

**Review by edwinnambaje — COMMENTED** [review]
Screenshot 2023-07-27 at 12 02 22
what's the use of this blue color at the buttom?

**Review by UwaweTera — APPROVED** [review]

**Review by patsicko — APPROVED** [review]

**Review by edwinnambaje — APPROVED** [review]

**Review by AbdulKhaliq59 — APPROVED** [review]
LGTM

**Review by blackd44 — APPROVED** [review]

**Review by Luciefifi — APPROVED** [review]

**Review by ceelogre — CHANGES_REQUESTED** [review]
The width is not divided evenly among two divs.
image
Also, remove the build folder.

**Review by ceelogre — APPROVED** [review]

**Pull request merged**
