### PR TITLE
Fix Uncompiled Templates & Documentation

### PR DESCRIPTION
**Pull request by patsicko**
# PR Description
- Create Docs component
- Create Support component
- Connect the created components to their respective routes 

# Description of tasks that were expected to be completed
- The task was to render the pages that were showing 404 error to the UI
-  Work on documentation for trainee, coordinator and admin
# How has this been tested?
.- Checkout into this branch `` fix-uncompiled-templates `` and run `` npm run dev `` then signin on UI and click on Docs or Help. The right contents will be loaded rather than showing 404 page not found.
- Login with right credentials as admin, coordinator or trainee, click on Docs link in sidebar. You will see the links that lead you to the tables from which right documentations will be displayed as models
# Number of Commits
2

The number of commits should not exceed **2 commits**. In case they are more than that, please take your time and squash them.

# Screenshots (If appropriate)
docs
support

# Please check this Checklist before you submit your PR:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My code generate no warnings
- [x] My test coverage meet the set test coverage threshold
- [x] There are no vulnerabilities
- [x] There are no conflicts with the base branch

### CODE REVIEW

**Review by AbdulKhaliq59 — APPROVED** [review]
LGTM

**Review by UwaweTera — APPROVED** [review]

**Review by oliviertech212 — COMMENTED** [review]
add translations 

Screenshot 2023-07-14 at 07 44 27


 also, work on alignment here 

image

**Review by blackd44 — APPROVED** [review]

**Review by ceelogre — CHANGES_REQUESTED** [review]
Unable to login
image

**Review by oliviertech212 — APPROVED** [review]

**Comment by ceelogre** [comment]
The admin and coordinator see the same docs. From an admin perspective, it doesn't make sense to tell them about how to rate since it's not their task, we should have content that is specific to them. **This can be done in v2 of docs** for now, work on these two items:


The first paragraph talks about ratings from a trainee's perspective yet the currently logged in user is an admin.
image


A section about adding meeting attendants is missing here:
image

It looks like "how to rate trainees" and "how to create calendar" are under the first list item. Add indentation to visually differentiate it from "how to grant permission"

image

**Review by ceelogre — APPROVED** [review]

**Pull request merged**
