### PR TITLE
fix CTA button get started

### LINKED ISSUE #139: CTA button on homepage is inactive
# Description

Clicking this button does not start any action. Let's have it redirect a user to another page, like login.
image

### PR DESCRIPTION
**Pull request by Himbaza123h**
# PR Description

1. This PR is for fixing CTA button(Get Started)
2. It will redirect a user to another page(Create new Organization)
3. Fix also some issues on sidebar for both users.

# How has this been tested?

1. Open The review app link.
4.  Go to homepage and check if `Get Started` redirect you to other Page(Create a new organization).
5. Check if it works in all kind of devices(Responsiveness).

# Screenshots (If appropriate)

Screen Shot 2022-11-08 at 19 20 58

### CODE REVIEW

**Comment by elissaihimbazwe** [comment]
I deployed a review app for you to try out this pull request 👇🏽
Heroku App: https://devpulse-review-app-162.herokuapp.com/


<hidden purpose="for-rewritable-pr-comment-action-use" value="Deploy"></hidden>

**Review by Placide123 — CHANGES_REQUESTED** [review]
It is working but check the responsiveness of the register organisation of the phone and tablet, it has some issue.

**Review by Francoise02 — APPROVED** [review]
This looks good @Himbaza123h the home page and organization login pages are well connected with the `Get started` button.

**Review by Placide123 — APPROVED** [review]

**Review by alicepretty — APPROVED** [review]

**Review by elissaihimbazwe — APPROVED** [review]
It looks fine👍🏼

**Review by ceelogre — CHANGES_REQUESTED** [review]
Why does it look like you changed a lot of files? Did you need to?

**Comment by Himbaza123h** [comment]
> changes



> Why does it look like you changed a lot of files? Did you need to?

No, I didn't , it is only that I squashed Ithe last commits on previous task.. but I didn't change anything apart from what I was supposed to work on..

**Review by ceelogre — CHANGES_REQUESTED** [review]
Once a user is logged in, this button is not clickable.
image

**Comment by Himbaza123h** [comment]
> Once a user is logged in, this button is not clickable. 
Screen Shot 2022-11-08 at 19 20 58


If it is this for `Continue` it is working, you can check again, Unless it is another button. and also the pricing menu is no longer available when user is loggedIn

**Review by Julienish14 — APPROVED** [review]

**Review by ceelogre — APPROVED** [review]

**Pull request merged**
