### PR TITLE
Fix trainee dashboard

### PR DESCRIPTION
**Pull request by Julesbi**
# PR Description
Internationalization of trainee dashboard and fixing alignment of items
# Description of tasks that were expected to be completed
- [x] Interantionalization of trainee dashboard
- [x] Fixing of aignment of sidebar with contents on the right section of an admin
# How has this been tested?
Use this [link](https://devpulse-review-app-47.herokuapp.com/) for reviewing this PR
Sign in as a trainee and change languagage to test Internationalization
Sign in as an admin and  see how items are aligned

### CODE REVIEW

**Comment by feyton** [comment]
I deployed a review app for you to try out this pull request 👇🏽

Heroku App: https://devpulse-review-app-47.herokuapp.com/


<hidden purpose="for-rewritable-pr-comment-action-use" value="Deploy"></hidden>

**Review by samyshyaka — APPROVED** [review]

**Review by chanceDira — CHANGES_REQUESTED** [review]
@Julesbi looks like something is wrong with the table alignment.
Also look at the second picture I think there are some changes on the table margin,

Screen Shot 2022-07-29 at 09 15 34

Screen Shot 2022-07-29 at 09 16 29

**Review by jeandamascyifuzo — APPROVED** [review]
Good job @Julesbi

**Review by chanceDira — APPROVED** [review]

**Review by ceelogre — APPROVED** [review]

**Comment by ceelogre** [comment]
Checkout [this](https://github.com/atlp-rwanda/atlp-pulse-fn/issues/52) issue and increase coverage before merging.

**Pull request merged**
