### PR TITLE
Ft trainee details

### PR DESCRIPTION
**Pull request by ishimweeli**
# PR Description
display trainees details to coordinator
Please include a brief description of the pull request you want to raise.
this pr displays trainee details to coordinator
# Description of tasks that were expected to be completed
click on details option and see trainee details
List all the tasks and sub-tasks that were assigned to you or that you assigned yourself. Make sure you check evey completed task.

# How has this been tested?

Please describe the tests that you ran to verify your functionalities. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

# Number of Commits
1
The number of commits should not exceed **2 commits**. In case they are more than that, please take your time and squash them.

# Screenshots (If appropriate)

# Please check this Checklist before you submit your PR:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My code generate no warnings
- [ ] My test coverage meet the set test coverage threshold
- [ ] There are no vulnerabilities
- [ ] There are no conflicts with the base branch

### CODE REVIEW

**Comment by elissaihimbazwe** [comment]
I deployed a review app for you to try out this pull request 👇🏽
Heroku App: https://devpulse-review-app-157.herokuapp.com/


<hidden purpose="for-rewritable-pr-comment-action-use" value="Deploy"></hidden>

**Review by alicepretty — APPROVED** [review]

**Review by ceelogre — DISMISSED** [review]
It seems there are seeded trainees after login as coordinator.

image

**Review by Julienish14 — COMMENTED** [review]
Eliab, good job. Your design looks good now, 
But little border radius and change to dark mode will be great.  
happy coding.

**Review by Placide123 — DISMISSED** [review]
good job Eliab , but try to fix how the image looks on this model and make it fit into its container as you see on the screen it is stretched somehow.
Screen Shot 2022-11-07 at 10 32 23

**Review by Julienish14 — APPROVED** [review]
Great Job Eliab, for me this looks good

**Review by Placide123 — APPROVED** [review]

**Review by Himbaza123h — APPROVED** [review]

**Review by elissaihimbazwe — APPROVED** [review]

**Review by Francoise02 — APPROVED** [review]

**Review by ceelogre — DISMISSED** [review]
It doesn't look like we are collecting the fields you added like country and city. I suggest we have at least these fields:
`{
name,
email, 
joined,
stage/phase,
cohort (current),
manager
}`

**Review by ceelogre — APPROVED** [review]
Any required changes will be implemented in the profile fix.

**Pull request merged**
