### PR TITLE
DP-109 feat: Create rating system Integration

### LINKED ISSUE #97: Create a rating system
The feature of creating a rating system should be integrated with the frontend

### PR DESCRIPTION
**Pull request by Julesbi**
admin is able to query all rating sytems

# PR Description
This PR is used to integrate the page accessible to an admin where he/she will be able to create rating(grading) systems.
# Description of tasks that were expected to be completed

- [x] Admin is be able to query all rating systems 
- [x] Admin is able to create a rating system

# How has this been tested?

- Sign in as an admin 
- Navigate on grading system using the navbar
- Query rating systems using a dropdown
- Click on custom to add new rating system
- Use a dropdown to check if the addded rating system is there

-Screenshots (If appropriate)

Refer to this image to know how grading system are added.

Screenshot (188)

### CODE REVIEW

**Comment by feyton** [comment]
I deployed a review app for you to try out this pull request 👇🏽
Heroku App: https://devpulse-review-app-91.herokuapp.com/


<hidden purpose="for-rewritable-pr-comment-action-use" value="Deploy"></hidden>

**Review by Dev-nkundineza — APPROVED** [review]
Good work @Julesbi

**Review by Dev-nkundineza — APPROVED** [review]
Good work @Julesbi , but solve the conflict

**Review by PatrickTUy — CHANGES_REQUESTED** [review]
nice work @Julesbi , try to make  this grading system more intuitive by giving out some examples in the placeholder, also when someone decides not to use the grading system anymore or they made a mistake , provide them some way to delete or edit it.

**Pull request closed without merging**
