### PR TITLE
#DP-89: (Feat) Homepage translation

### PR DESCRIPTION
**Pull request by feyton**
### What the PR does:
This PR add the ability to change the language directly from the homepage. This will fix an issue of requiring a user that they login before being able to change the language.

### Tasks completed

- [x] Adds the ability to switch language
- [x] The language switch shows active language
- [x] Closes 44

### How should this be manually tested
This feature can easily be tested by changing the language from the footer of the page and examining the changes in the UI

### Screenshots
Not applicable

### CODE REVIEW

**Comment by feyton** [comment]
I deployed a review app for you to try out this pull request 👇🏽

Heroku App: https://devpulse-review-app-51.herokuapp.com/


<hidden purpose="for-rewritable-pr-comment-action-use" value="Deploy"></hidden>

**Review by PatrickTUy — APPROVED** [review]
This looks good

**Review by chanceDira — APPROVED** [review]
Awesome

**Review by PatrickTUy — DISMISSED** [review]
can you fix the opacity of the navbar and also raise the test, so as to pass all the checks.

**Review by jeandamascyifuzo — APPROVED** [review]
good job

**Review by samyshyaka — APPROVED** [review]

**Review by ceelogre — APPROVED** [review]

**Pull request merged**
