### PR TITLE
TTLs Page

### PR DESCRIPTION
**Pull request by AbdulKhaliq59**
# PR Description

This PR is used to create TTLs page

# Description of tasks that were expected to be completed

- [x] A role of TTL is added
- [x] New users can assigned the TTL role
- [x] A TTL page is added after "Coordinators" page
- [x] TTL page should list all TTLs in a paginated format with teams they manage 

# How has this been tested?
- run `npm run dev`
- Login as `admin`
- Go on `Role Accesss`
- assign user `TTL` role 
- Go on TTLs Page

# Screenshots (If appropriate)
Screenshot 2023-07-19 at 16 46 59

Screenshot 2023-07-19 at 16 41 14

# Please check this Checklist before you submit your PR:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My code generate no warnings
- [x] My test coverage meet the set test coverage threshold
- [x] There are no vulnerabilities
- [x] There are no conflicts with the base branch

### CODE REVIEW

**Review by ericndungutse — APPROVED** [review]
LGTM

**Review by patsicko — DISMISSED** [review]
You did a great job Abdoul, however to see the updates on TTLs page requires to refresh the page. Can you change this to be rendered directly?

**Review by Luciefifi — APPROVED** [review]

**Review by Habihirwe — APPROVED** [review]

**Review by ceelogre — CHANGES_REQUESTED** [review]
How can I assign a TTL to a coordinator under the admin account? How can I perform CRUD operations on a TTL account?

**Review by ceelogre — CHANGES_REQUESTED** [review]
I'm unable to click any of the buttons in the Action list.
image
We talked about being able to assign a TTL to a team. Since I'm unable to click the Action items, I can't tell if it's working or not.

**Comment by ceelogre** [comment]
There is a problem with styling. Could you first look into it and find out why?
image

**Comment by ceelogre** [comment]
I assigned a user the role of a TTL then used their account to login. This is the error message that appeared.
The account is: twesimartha@gmail.com
image

**Review by ceelogre — APPROVED** [review]

**Pull request merged**
