### PR TITLE
Ft forgot password

### PR DESCRIPTION
**Pull request by Francoise02**
# PR Description

A feature that allows users to reset their password in case they have forgotten

# Description of tasks that were expected to be completed

- Design reset password page
- Create the frontend page to reset the password
- Work on the backend functionality for the page
- Integrate the page with the backend functionality

# How has this been tested?

Please describe the tests that you ran to verify your functionalities. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

# Number of Commits

**1 commit**. 
# Screenshots (If appropriate)

# Please check this Checklist before you submit your PR:

- [ ✔️] My code follows the style guidelines of this project
- [ ✔️] I have performed a self-review of my code
- [ ✔️] I have commented my code, particularly in hard-to-understand areas
- [ ✔️] My code generate no warnings
- [ ✔️] My test coverage meet the set test coverage threshold
- [ ✔️] There are no vulnerabilities
- [ ✔️] There are no conflicts with the base branch

### CODE REVIEW

**Comment by elissaihimbazwe** [comment]
I deployed a review app for you to try out this pull request 👇🏽
Heroku App: https://devpulse-review-app-161.herokuapp.com/


<hidden purpose="for-rewritable-pr-comment-action-use" value="Deploy"></hidden>

**Review by Julienish14 — APPROVED** [review]

**Review by ishimweeli — APPROVED** [review]

**Review by ishimweeli — CHANGES_REQUESTED** [review]
it seems that there is issue with inviting user the link can not be opened

**Review by elissaihimbazwe — APPROVED** [review]

**Review by Placide123 — APPROVED** [review]

**Review by ishimweeli — APPROVED** [review]

**Review by ceelogre — CHANGES_REQUESTED** [review]
Usually, systems don't disclose whether emails exist or not (for the same reason when loggin, they don't tell you which one between username and password is wrong). Just tell them that if the email address exist with us, they will receive a reset email. Also, the message is not translated. Also, when you press return after entering an email, the form is not submitted instead the page is  reloaded.
forgot key 3

Why is the link outside the email body? This might lead to email spam filters to flag it
forgot key
This page is not properly formatted, this also leads to unexpected click behaviors.

 
forgot key 2

**Review by alicepretty — APPROVED** [review]

**Review by alaintresor — APPROVED** [review]

**Review by alaintresor — APPROVED** [review]

**Review by ceelogre — CHANGES_REQUESTED** [review]
I'm unable to login so I can create a new trainee.
image

**Review by ceelogre — APPROVED** [review]

**Pull request merged**
