### PR TITLE
Fix logout and settings

### LINKED ISSUE #106: fix logout & settings
On mobile devices the logout and settings Icons dissapear whereas they should be visible to allow the user to access logout and settings

### PR DESCRIPTION
**Pull request by Francoise02**
# PR Description
This PR fixes the issue of logout and settings icons responsiveness on the dashboard.
# Description of tasks that were expected to be completed
- Fix the logout and settings icons on the small screens.
# How has this been tested?
Please describe the tests that you ran to verify your functionalities. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.
# Number of Commits
The number of commits should not exceed **2 commits**. In case they are more than that, please take your time and squash them.
# Screenshots (If appropriate)
Screenshot (1026)

# Please check this Checklist before you submit your PR:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My code generate no warnings
- [ ] My test coverage meet the set test coverage threshold
- [ ] There are no vulnerabilities
- [ ] There are no conflicts with the base branch

### CODE REVIEW

**Comment by Procech20** [comment]
I deployed a review app for you to try out this pull request 👇🏽

Heroku App: https://devpulse-review-app-134.herokuapp.com/


<hidden purpose="for-rewritable-pr-comment-action-use" value="Deploy"></hidden>

**Review by Placide123 — APPROVED** [review]

**Review by PatrickTUy — APPROVED** [review]
This looks good!

**Review by Dev-nkundineza — CHANGES_REQUESTED** [review]
when clicking on settings icon , the sidebar is still fixed. which is different from other menus
Screen Shot 2022-10-13 at 12 44 14

**Review by ceelogre — CHANGES_REQUESTED** [review]
Unable to login to the org
image

**Review by ceelogre — APPROVED** [review]

**Review by Dev-nkundineza — APPROVED** [review]
Good work @Francoise02

**Pull request merged**
