### PR TITLE
Fix add favicon to show on Safari and DuckDuckGo

### PR DESCRIPTION
**Pull request by IIshimwe**
# PR Description
Usually, the favicon is showing in other browsers but not in Safari and DuckDuckGo, so this PR is for showing the favicon in Safari and DuckDuckGo browsers as well.
# Description of tasks that were expected to be completed
- Showing favicon in Safari and DuckDuckGo browsers.
# How has this been tested?
Clone [DevPulse v2.0.0 Frontend repo](https://github.com/atlp-rwanda/atlp-pulse-fn)
open it in your preferred code editor
git switch fix-add-favicon-dp-97
npm install
npm run dev
**Note:** You must be having an apple product to have a Safari browser and be using the DuckDuckGo browser.
# Number of Commits
1
# Screenshots (If appropriate)
Comming soon.

### CODE REVIEW

**Comment by feyton** [comment]
I deployed a review app for you to try out this pull request 👇🏽

Heroku App: https://devpulse-review-app-92.herokuapp.com/


<hidden purpose="for-rewritable-pr-comment-action-use" value="Deploy"></hidden>

**Review by feyton — APPROVED** [review]
@IIshimwe 

This is great work

**Review by chanceDira — APPROVED** [review]

**Review by jeandamascyifuzo — APPROVED** [review]
well done @IIshimwe

**Comment by ceelogre** [comment]
No bandwith to work on this now.

**Pull request closed without merging**
